[build]
  environment = { VITE_GEMINI_API_KEY = "AIzaSyBqvOB3JDYHFeXbGlMPTarGr7odLMigso0", VITE_GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent" }

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
